apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm
  namespace: ai-infer
spec:
  template:
    spec:
      containers:
      - name: vllm
        image: vllm/vllm-openai:v0.5.5
        env:
        - name: CUDA_VISIBLE_DEVICES
          value: "0"
        - name: VLLM_DEVICE
          value: "cuda"