version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-nvme
    environment:
      - OLLAMA_MODELS=/root/.ollama/models
      - OLLAMA_HOST=0.0.0.0:11434
    volumes:
      # Map NVMe storage to container's models directory
      - /mnt/nvme/ollama:/root/.ollama/models
      # For GPU support
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    networks:
      - ai-network

  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-webui
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - ollama-webui-data:/app/backend/data
    ports:
      - "8080:8080"
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - ai-network

networks:
  ai-network:
    driver: bridge

volumes:
  ollama-webui-data: