apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-infer
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: vllm
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "10"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "5"