apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm
  namespace: ai-infer
spec:
  template:
    spec:
      initContainers:
      - name: nvme-verify
        image: nvme-models:local
        imagePullPolicy: Never
      containers:
      - name: nvme-metrics
        image: nvme-models:local
        imagePullPolicy: Never