apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm
  namespace: ai-infer
spec:
  template:
    spec:
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: "2Gi"
      containers:
      - name: vllm
        volumeMounts:
        - name: dshm
          mountPath: /dev/shm