apiVersion: v1
kind: ServiceAccount
metadata:
  name: nvme-model-server
  namespace: ai-infer
  labels:
    app: nvme-model-server
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nvme-model-server
  namespace: ai-infer
rules:
# Minimal permissions - add only what's needed
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["nvme-model-config"]
  verbs: ["get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nvme-model-server
  namespace: ai-infer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nvme-model-server
subjects:
- kind: ServiceAccount
  name: nvme-model-server
  namespace: ai-infer