apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nvme-model-server
  namespace: ai-infer
  labels:
    app: nvme-model-server
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: nvme-model-server
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    scheme: http