apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gpt-oss20b-llamacpp
  labels:
    app: gpt-oss20b-llamacpp
    release: prometheus
spec:
  selector:
    matchLabels:
      app: gpt-oss20b-llamacpp
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
