apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: vllm-ai-alerts
  namespace: monitoring
spec:
  groups:
  - name: gpu-and-vllm
    rules:
    - alert: GPUMemoryHigh
      expr: DCGM_FI_DEV_FB_USED / DCGM_FI_DEV_FB_TOTAL > 0.92
      for: 5m
      labels: { severity: warning }
      annotations:
        summary: "GPU memory >92% for 5m on {{ $labels.hostname }}"
    - alert: VllmTargetDown
      expr: up{job="vllm"} == 0
      for: 2m
      labels: { severity: critical }
      annotations:
        summary: "vLLM target down"