name: Security Pipeline

on:
  push:
    branches: [ main, develop, "feature/*" ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read
  security-events: write   # required for upload-sarif

jobs:
  security:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2

      - name: Semgrep SAST
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto

      # 1) Produce SARIF regardless of findings (do not fail yet)
      - name: Trivy FS scan (produce SARIF)
        id: trivy-sarif
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          ignore-unfixed: true
          format: sarif
          output: trivy-results.sarif
          severity: HIGH,CRITICAL
        continue-on-error: true

      - name: Upload Trivy SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

      # 2) Enforce policy after upload (fail build on HIGH/CRITICAL)
      - name: Trivy FS scan (enforce policy)
        id: trivy-enforce
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          ignore-unfixed: true
          format: table
          severity: HIGH,CRITICAL
          exit-code: 1
        continue-on-error: true

      - name: Fail if HIGH/CRITICAL vulns were found
        if: steps.trivy-enforce.outcome == 'failure'
        run: |
          echo "::error::Trivy found HIGH/CRITICAL vulnerabilities"
          exit 1

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@v2
      
      - name: Security scan summary
        if: always()
        run: |
          echo "=== Security Scan Summary ==="
          echo "✅ Security scanning completed"
          echo "Check the results above for any findings"
          echo "All CRITICAL and HIGH severity issues must be resolved"